# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1078, 600)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left = QtWidgets.QLabel(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(30, 80, 340, 491))
        self.left.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;")
        self.left.setText("")
        self.left.setObjectName("left")
        self.right = QtWidgets.QLabel(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(370, 80, 490, 490))
        self.right.setStyleSheet("border-image: url(:/img/resourse/Login_right.jpg);\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;\n"
"")
        self.right.setText("")
        self.right.setObjectName("right")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 80, 490, 490))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(150, 140, 88, 43))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(32)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 230, 211, 41))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0, 0, 0, 100);\n"
"background-color: rgba(0, 0, 0,0);")
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 330, 211, 41))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineEdit_2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0, 0, 0, 100);\n"
"background-color: rgba(0, 0, 0,0);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 450, 101, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color:qlineargradient(spradient:pad,x1:0,y1:0,x2:1,y2:1,stop:0\n"
"rgba(102,133,156,255),stop:1 rgba(117,255,201,255));\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px:\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 100, 32, 32))
        self.pushButton_2.setStyleSheet("border-image: url(:/icon/resourse/minus.png);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:8px;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(780, 100, 32, 32))
        self.pushButton_3.setStyleSheet("border-image: url(:/icon/resourse/close.png);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:8px;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 150, 351, 81))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(25)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(410, 210, 351, 81))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(25)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(90, 450, 101, 51))
        self.pushButton_1.setStyleSheet("QPushButton{\n"
"    background-color:qlineargradient(spradient:pad,x1:0,y1:0,x2:1,y2:1,stop:0\n"
"rgba(248,187,208,255),stop:1 rgba(187,222,251,255));\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px:\n"
"}\n"
"")
        self.pushButton_1.setObjectName("pushButton_1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_3.clicked.connect(MainWindow.close)
        self.pushButton_2.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "你好"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "账号："))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "密码："))
        self.pushButton.setText(_translate("MainWindow", "登录"))
        self.label_5.setText(_translate("MainWindow", "作者：Hundred_Dreams"))
        self.label_6.setText(_translate("MainWindow", "感谢使用awa"))
        self.pushButton_1.setText(_translate("MainWindow", "注册"))
import need.res_rc
