# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewMainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 960, 540))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(92, 170, 255, 255), stop:1 rgba(255, 170, 255, 255));\n"
"\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 980, 560))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0,30);\n"
"\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 960, 70))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255,40);\n"
"border-top-left-radius:20px;\n"
"\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 80, 960, 3))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.progressBar.setFont(font)
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setStyleSheet("QProgressBar { border: 2px; border-radius: 5px; background-color: #b3e5fc; text-align: center;}QProgressBar::chunk {background:QLinearGradient(x1:0,y1:0,x2:2,y2:0,stop:0 #b3e5fc,stop:1  #f06292); }")
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 141, 470))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255,50);\n"
"border-bottom-left-radius:20px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.home = QtWidgets.QPushButton(self.centralwidget)
        self.home.setGeometry(QtCore.QRect(20, 110, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home.sizePolicy().hasHeightForWidth())
        self.home.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        font.setPointSize(14)
        font.setItalic(False)
        font.setKerning(False)
        self.home.setFont(font)
        self.home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.home.setStyleSheet("background-color: rgba(255, 255, 255,50);\n"
"border:1px solid rgba(255, 170, 255, 75);\n"
"border-radius:8px;\n"
"text-align:left")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/home_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon)
        self.home.setIconSize(QtCore.QSize(36, 36))
        self.home.setCheckable(False)
        self.home.setObjectName("home")
        self.shuapingqi = QtWidgets.QPushButton(self.centralwidget)
        self.shuapingqi.setGeometry(QtCore.QRect(20, 170, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shuapingqi.sizePolicy().hasHeightForWidth())
        self.shuapingqi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        font.setPointSize(14)
        font.setItalic(False)
        font.setKerning(False)
        self.shuapingqi.setFont(font)
        self.shuapingqi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shuapingqi.setStyleSheet("background-color: rgba(255, 255, 255,50);\n"
"border:1px solid rgba(255, 170, 255, 75);\n"
"border-radius:8px;\n"
"text-align:left")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/sort_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuapingqi.setIcon(icon1)
        self.shuapingqi.setIconSize(QtCore.QSize(36, 36))
        self.shuapingqi.setCheckable(False)
        self.shuapingqi.setObjectName("shuapingqi")
        self.min = QtWidgets.QPushButton(self.centralwidget)
        self.min.setGeometry(QtCore.QRect(880, 30, 24, 24))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.min.setFont(font)
        self.min.setStyleSheet("border-image: url(:/icons/icons/remove_FILL0_wght400_GRAD0_opsz24.png);")
        self.min.setText("")
        self.min.setObjectName("min")
        self.close_2 = QtWidgets.QPushButton(self.centralwidget)
        self.close_2.setGeometry(QtCore.QRect(920, 30, 24, 24))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.close_2.setFont(font)
        self.close_2.setStyleSheet("border-image: url(:/icons/icons/close_FILL0_wght400_GRAD0_opsz24.png);")
        self.close_2.setText("")
        self.close_2.setObjectName("close_2")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(40, 25, 191, 41))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(160, 90, 801, 451))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(70, 10, 681, 341))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        font.setPointSize(30)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.widget_2 = QtWidgets.QWidget(self.page_2)
        self.widget_2.setGeometry(QtCore.QRect(250, 40, 330, 41))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_1 = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("#pushButton_1{\n"
"    border:none;\n"
"    border:1px solid rgba(0,0,0,50);\n"
"    border-radius:6px\n"
"}\n"
"#pushButton_1:focus{\n"
"    color:rgb(111,111,111);\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    border:none;\n"
"    border:1px solid rgba(0,0,0,50);\n"
"    border-radius:6px\n"
"}\n"
"#pushButton_2:focus{\n"
"    color:rgb(111,111,111);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"    border:none;\n"
"    border:1px solid rgba(0,0,0,50);\n"
"    border-radius:6px\n"
"}\n"
"#pushButton_3:focus{\n"
"    color:rgb(111,111,111);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(180, 130, 471, 291))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.stackedWidget_2.setFont(font)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.widget_3 = QtWidgets.QWidget(self.page_3)
        self.widget_3.setGeometry(QtCore.QRect(70, 10, 330, 260))
        self.widget_3.setObjectName("widget_3")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 320, 40))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 85, 320, 40))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 190, 301, 51))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.widget_4 = QtWidgets.QWidget(self.page_4)
        self.widget_4.setGeometry(QtCore.QRect(70, 10, 331, 251))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.widget_4.setFont(font)
        self.widget_4.setObjectName("widget_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 0, 320, 40))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(0, 60, 320, 40))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(0, 120, 320, 40))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 190, 301, 51))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.widget_5 = QtWidgets.QWidget(self.page_5)
        self.widget_5.setGeometry(QtCore.QRect(70, 10, 331, 251))
        self.widget_5.setObjectName("widget_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_7.setGeometry(QtCore.QRect(0, 0, 320, 40))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_8.setGeometry(QtCore.QRect(0, 85, 320, 40))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 190, 301, 51))
        font = QtGui.QFont()
        font.setFamily("OPlusSans 3.0")
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("#pushButton_6{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget_2.addWidget(self.page_5)
        self.stackedWidget.addWidget(self.page_2)
        self.label_2.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.progressBar.raise_()
        self.label_3.raise_()
        self.home.raise_()
        self.shuapingqi.raise_()
        self.min.raise_()
        self.close_2.raise_()
        self.title.raise_()
        self.stackedWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.min.clicked.connect(MainWindow.showMinimized)
        self.close_2.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home.setText(_translate("MainWindow", "主页"))
        self.shuapingqi.setText(_translate("MainWindow", "刷屏器"))
        self.title.setText(_translate("MainWindow", "寒澈工具箱"))
        self.label_5.setText(_translate("MainWindow", "Welcome!\n"
"\n"
"欢迎使用寒澈工具箱(*^▽^*)\n"
"请在左边的工具栏选择你需要的工具。"))
        self.pushButton_1.setText(_translate("MainWindow", "刷剪贴板"))
        self.pushButton_2.setText(_translate("MainWindow", "刷指定内容"))
        self.pushButton_3.setText(_translate("MainWindow", " 刷表情包（连点）"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "刷屏次数"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "停顿时间"))
        self.pushButton_4.setText(_translate("MainWindow", "开始刷屏"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "刷屏内容"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "刷屏次数"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "停顿时间"))
        self.pushButton_5.setText(_translate("MainWindow", "开始刷屏"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "刷屏次数"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "停顿时间"))
        self.pushButton_6.setText(_translate("MainWindow", "开始刷屏"))
import need.NewRes_rc
