# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_update(object):
    def setupUi(self, MainWindow_update):
        MainWindow_update.setObjectName("MainWindow_update")
        MainWindow_update.setEnabled(True)
        MainWindow_update.resize(448, 281)
        font = QtGui.QFont()
        font.setPointSize(20)
        MainWindow_update.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow_update)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 190, 381, 31))
        self.progressBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 211, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 411, 231))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.progressBar.raise_()
        self.label.raise_()
        MainWindow_update.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_update)

    def retranslateUi(self, MainWindow_update):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_update.setWindowTitle(_translate("MainWindow_update", "MainWindow"))
        self.label.setText(_translate("MainWindow_update", "获取更新中……"))
